name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.

dependencies:
  flutter:
    sdk: flutter
  flutter_blue:
    path: ../

flutter:
  uses-material-design: true