/*----------------------------------------------------------------------------
 *
 * File:
 * host_src\eas_build.h
 *
 * Contents and purpose:
 * This file contains the build configuration for this
 * build. The buildGUIDStr is a GUID created during
 * the build process and is guaranteed to be unique
 * for each build.
 *
 * Copyright Sonic Network Inc. 2006

 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was autogenerated by buildid.exe
 *----------------------------------------------------------------------------
*/

#ifndef _GUID_1feda229b9a845e996f473c0a80e7220_
#define _GUID_1feda229b9a845e996f473c0a80e7220_

#define _BUILD_VERSION_ "1feda229-b9a8-45e9-96f4-73c0a80e7220"
#define _BUILD_TIME_ 0x4743badd

#endif /* _GUID_1feda229b9a845e996f473c0a80e7220_ */
